openapi: 3.1.0
info:
  title: Ekang API
  version: 1.0.0
servers:
  - description: Production server
    url: https://ekang-api.herokuapp.com/v{version}
    variables:
      version:
        descriptions: Major version of the API
        default: '1'
  - description: Local server
    url: http://{host}:{port}/v{version}
    variables:
      host:
        descriptions: Server's host
        default: localhost
        enum: [ 0.0.0.0, localhost ]
      port:
        descriptions: Server's port
        default: '8080'
      version:
        descriptions: Major version of the API
        default: '1'
tags:
  - name: Translations
    description: Operations related to translations.
  - name: Work in progress
    description: Operations that we are currently building.
paths:
  translations:
    $ref: paths/translations.yml
components:
  schemas:
    Translation:
      $ref: components/schemas/translation.yml
