name: Continuous Integration
on:
  push:
    branches: [ master ]
    paths:
      - '**/*.kts'
      - '**/src/**'
      - '*gradle*'
      - .dockerignore
      - .github/workflows/*
      - Dockerfile
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew test --no-daemon
