name: Deployment
on:
  push:
    branches: [ master ]
    paths: [ .github/workflows/deployment.yml ]
  workflow_dispatch:
  workflow_run:
    workflows: [ Delivery ]
    types: [ completed ]
jobs:
  deploy:
    name: Deploy image in production
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sudo sh
      - name: Login to Heroku
        env:
          FILE: .netrc
          LOGIN: ${{ secrets.HEROKU_LOGIN }}
          TOKEN: ${{ secrets.HEROKU_TOKEN }}
        run: echo "machine api.heroku.com" > $FILE &&
          echo "  login $LOGIN" >> $FILE &&
          echo "  password $TOKEN" >> $FILE &&
          echo "machine git.heroku.com" >> $FILE &&
          echo "  login $LOGIN" >> $FILE &&
          echo "  password $TOKEN" >> $FILE
      - name: Deploy image
        env:
          HEROKU_APP: ekang-api
        run: heroku container:release web -a $HEROKU_APP
