name: Integration
on:
  push:
    branches: [ master ]
    paths: [ '*.kts', '*gradle*', .github/workflows/*, src/** ]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run tests
        run: ./gradlew test --no-daemon
